prometheus:
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  configmapReload:
    prometheus:
      enabled: false
  server:
    nodeSelector:
      kubernetes.io/hostname: pi-server-1
    persistentVolume:
      enabled: true
      existingClaim: "prometheus-pvc"
      volumeName: "prometheus-pv"
